// Field definitions for tooltips and help text

export const FIELD_DEFINITIONS = {
  // Deal Assumptions
  askingOrOfferPrice: "The seller's asking price or your proposed offer amount for the business.",
  annualRevenue: "Total annual revenue (top-line sales) generated by the business in the most recent full year.",
  annualCashFlow: "Seller's Discretionary Earnings (SDE) or EBITDA - the cash flow available after operating expenses but before owner compensation and debt service.",
  ffeValue: "Furniture, Fixtures & Equipment - tangible assets like machinery, computers, furniture, and other equipment.",
  inventoryValue: "Current value of inventory on hand (raw materials, work-in-progress, finished goods).",
  realEstateValue: "Fair market value of any real estate associated with the business (building, land).",
  annualRentsPaidToOwnerRE: "Annual rent paid to the owner for use of real estate. This is added back to cash flow if you're buying the property.",

  // Business Assumptions
  buyersMinimumSalary: "Your required salary from the business to maintain your standard of living. This reduces cash available for debt service.",
  workingCapitalRequirement: "Cash needed for day-to-day operations (inventory, receivables, operating expenses). Typically 1-3 months of operating costs.",
  annualCapexMaintenance: "Annual capital expenditures needed to maintain the business at its current level (replace equipment, maintain facilities).",
  annualCapexNewInvestments: "Annual capital expenditures for growth and expansion (new equipment, facility improvements, technology upgrades).",

  // Financing
  buyerEquity: "Your down payment - cash you're investing from personal funds, partners, or investors.",
  sellerFinancing: "Amount the seller is financing (seller note). Typically stands behind SBA loan and may require standby agreement.",
  termLoan: "Traditional term loan amount, typically from SBA 7(a) or conventional financing.",
  revolvingLOC: "Revolving line of credit for working capital needs. You only pay interest on the amount drawn.",
  closingCosts: "Transaction costs including SBA guarantee fee, bank fees, legal fees, due diligence, appraisal, and other closing expenses.",

  // Lender Analysis
  interestRateTermLoanAPR: "Annual percentage rate on the term loan. SBA 7(a) rates are typically Prime + 2.75% to Prime + 4.75%.",
  termYears: "Loan term in years. SBA 7(a) allows up to 10 years for business assets, 25 years for real estate.",
  interestRateLOCAPR: "Annual percentage rate on the line of credit. Typically higher than term loan rates.",
  locUtilizationPct: "Expected average utilization of your line of credit (percentage of total LOC that will be drawn). Conservative assumption is 35-50%.",

  // Calculated Metrics
  dscr: "Debt Service Coverage Ratio - measures how many times your cash flow can cover annual debt payments. Lenders typically require 1.25x minimum.",
  cashOnCashReturn: "Year 1 cash return divided by your equity investment. Shows the cash-on-cash yield on your down payment.",
  returnOnInvestment: "Net cash flow divided by total cash invested (equity + closing costs). Measures overall return on your investment.",
  leverageRatio: "Total debt divided by your equity. Shows how much you're borrowing relative to your own money. Higher leverage = more risk but potentially higher returns.",
  equityCaptureRate: "Your equity as a percentage of the purchase price. Shows how much 'skin in the game' you have.",
  purchasePriceToSDEMultiple: "Purchase price divided by annual cash flow (SDE/EBITDA). Industry benchmarks vary but typically 2.5x-4.5x for small businesses.",
  excessCashFlow: "Cash remaining after all debt service. This is your discretionary cash for owner distributions, reinvestment, or reserves.",

  // Sources & Uses
  sourcesTotal: "Total capital available from all sources (equity, seller note, bank financing).",
  usesTotal: "Total capital required for the transaction (purchase price, working capital, closing costs).",
  usesCashAtClosingToSeller: "Cash paid to seller at closing (after subtracting seller financing).",
};

// Get field definition
export function getFieldDefinition(fieldName: string): string {
  return FIELD_DEFINITIONS[fieldName as keyof typeof FIELD_DEFINITIONS] || "No definition available.";
}

// Category-based field groupings for legend
export const FIELD_CATEGORIES = {
  "Deal Structure": [
    "askingOrOfferPrice",
    "annualRevenue",
    "annualCashFlow",
    "ffeValue",
    "inventoryValue",
    "realEstateValue",
  ],
  "Operating Assumptions": [
    "buyersMinimumSalary",
    "workingCapitalRequirement",
    "annualCapexMaintenance",
    "annualCapexNewInvestments",
  ],
  "Financing": [
    "buyerEquity",
    "sellerFinancing",
    "termLoan",
    "revolvingLOC",
    "closingCosts",
  ],
  "Return Metrics": [
    "dscr",
    "cashOnCashReturn",
    "returnOnInvestment",
    "leverageRatio",
    "excessCashFlow",
  ],
};

// Industry benchmarks for reference
export const INDUSTRY_BENCHMARKS = {
  dscr: {
    minimum: 1.25,
    preferred: 1.35,
    excellent: 1.5,
    description: "Debt Service Coverage Ratio",
  },
  sdeMultiple: {
    low: 2.0,
    typical: 3.5,
    high: 5.0,
    description: "Purchase Price / SDE Multiple",
  },
  cashOnCashReturn: {
    minimum: 0.15,
    good: 0.25,
    excellent: 0.35,
    description: "Cash-on-Cash Return (15-35% typical)",
  },
  downPayment: {
    sbaMinimum: 0.10,
    typical: 0.15,
    strong: 0.25,
    description: "Down Payment as % of Purchase Price",
  },
};
